# Generated by Django 4.2.18 on 2026-03-29 13:28

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_city',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name="Notes de l'agence"),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='current_address',
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name='Adresse actuelle'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Date de naissance'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_name',
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name='Employeur / Établissement'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor_income',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name='Revenus mensuels du garant (€)'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor_name',
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name='Nom du garant'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor_on_smic',
            field=models.BooleanField(default=False, verbose_name='Garant au SMIC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_guarantor',
            field=models.BooleanField(default=False, verbose_name='A un garant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='CNI / Passeport'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name='Revenus mensuels nets (€)'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='payslip',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Fiche de paie'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='proof_of_address',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Justificatif de domicile'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='situation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('employe', 'Employé'),
                    ('independant', 'Indépendant / Auto-entrepreneur'),
                    ('etudiant', 'Étudiant'),
                    ('retraite', 'Retraité'),
                    ('sans_emploi', 'Sans emploi'),
                    ('autre', 'Autre')
                ],
                max_length=20,
                verbose_name='Situation professionnelle'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(
                choices=[
                    ('en_attente', 'En attente'),
                    ('valide', 'Validé'),
                    ('refuse', 'Refusé')
                ],
                default='en_attente',
                max_length=20,
                verbose_name='Statut du dossier'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
