# Generated by Django 4.2.18 on 2026-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0005_letting_reference'),
        ('profiles', '0004_remove_profile_favorite_city_profile_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_letting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='lettings.letting', verbose_name='Logement souhaité'),
        ),
    ]
