version: "3.11"

services:
  web:
    build: .
    container_name: oc-lettings-web
    ports:
      - "8000:8000"
    # Volume pour la DB SQLite (persistance)
    volumes:
      - db_data:/app/db.sqlite3
    env_file:
      - .env
    # Si tu veux garder la CMD du Dockerfile, tu peux l’omettre ici.
    # Sinon tu peux la redéfinir:
    # command: >
    #   sh -c "python manage.py migrate --noinput &&
    #          gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  db_data:
