# Generated by Django 4.2.18 on 2026-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_letting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='area',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Surface en m²',
                null=True),
        ),
        migrations.AddField(
            model_name='letting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='letting',
            name='price_per_night',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True),
        ),
        migrations.AddField(
            model_name='letting',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
