# Generated by Django 6.0.1 on 2026-01-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_alter_address_country_iso_code_alter_address_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
