# Generated by Django 4.2.18 on 2026-03-29 12:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_letting_area_letting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('letting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='lettings.letting')),
            ],
            options={
                'verbose_name': 'Image galerie',
                'verbose_name_plural': 'Images galerie',
                'ordering': ['order'],
            },
        ),
    ]
